source "/home/mikan919/.local/share/sheldon/repos/github.com/romkatv/zsh-defer/zsh-defer.plugin.zsh"
source "/home/mikan919/.local/share/sheldon/repos/gist.github.com/8439db6a608c3757a691245a6cc3e34b/.p10k.zsh"
source "/home/mikan919/.config/zsh/nonlazy/history.zsh"
source "/home/mikan919/.config/zsh/nonlazy/other.zsh"
source "/home/mikan919/.local/share/sheldon/repos/github.com/romkatv/powerlevel10k/powerlevel10k.zsh-theme"
zsh-defer source "/home/mikan919/.local/share/sheldon/repos/github.com/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
zsh-defer source "/home/mikan919/.local/share/sheldon/repos/github.com/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
zsh-defer source "/home/mikan919/.config/zsh/lazy/alias.zsh"
zsh-defer source "/home/mikan919/.config/zsh/lazy/env.zsh"
zsh-defer source "/home/mikan919/.config/zsh/lazy/utils.zsh"
