shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

# タイプ時の補完表示
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

# Starship Prompt
[plugins.starship]
inline = 'eval "$(starship init zsh)"'

# Mise (実行環境をまとめるやつ)
[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

# コマンドが存在するかとかのカラー表示
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
