# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]


[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.dracula-zsh-syntax-highlighting]
github = "dracula/zsh-syntax-highlighting"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.blackbox]
github = "StackExchange/blackbox"

[plugins.enhancd]
github = "b4b4r07/enhancd"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
