source "/home/mikan/.local/share/sheldon/repos/github.com/romkatv/zsh-defer/zsh-defer.plugin.zsh"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/romkatv/powerlevel10k/powerlevel10k.zsh-theme"
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/zsh-users/zsh-completions/zsh-completions.plugin.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/alias.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/compile.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/env.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/history.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/other.zsh"
zsh-defer source "/home/mikan/.config/zsh/lazy/utils.zsh"
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/paulirish/git-open/git-open.plugin.zsh"
zsh-defer source "/home/mikan/.local/share/sheldon/repos/github.com/hlissner/zsh-autopair/autopair.plugin.zsh"
